### ISSUE TITLE
Black sceen when loggin in with VNC

### ISSUE THREAD

**Issue by oholimoli** [zephyrproject-rtos/docker-image#26]
When I start the image and login with VNC I can see only a black screen.
I'm starting the container with this command: 

```
docker run -ti -p 5900:5900 -v D:\GitLab\smart-binary-sensing\o200.gp-zephyr:/workdir docker.io/zephyrprojectrtos/zephyr-build:latest
```

This is the output I get:

```
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
user@64d871c7a4d0:/workdir$
The VNC desktop is:      64d871c7a4d0:0
PORT=5900
```

I use Docker Desktop v2.2.0.4 Engine 19.03.8

**Comment by dltn** [comment]
The image doesn't start with Zephyr running; you need to build and run a Zephyr app with SDL display output before seeing anything over VNC.

It's confusing because the Docker output doesn't display the shell you've dropped into until after you press ENTER:

```
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
user@e09b7d56b175:/workdir/zephyr/aod_app/build$
The VNC desktop is:      e09b7d56b175:0
PORT=5900

user@e09b7d56b175:/workdir$
```

From there, you can follow the example from the README and you should see the LittlevGL demo appear on VNC:

```
cd samples/display/cfb
mkdir build
cd build
cmake -DBOARD=native_posix -GNinja ..
ninja run
```

**Comment by stephanosio** [comment]
Closing stale issue; please re-open if this is still an issue.
